config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static_pages#index'
  resources :courses, only: [:index, :show]
  resources :lessons, only: [:show]
  namespace :admin do
    resources :sections, only: [] do
      resources :lessons, only: [:new, :create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :sections
  
  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  mount_uploader :image, ImageUploader
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]
  
  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to admin_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to admin_course_path(current_section.course)
  end

  private

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle)
  end

end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course

  def new
    @section = Section.new
  end

  def create
    @section = current_course.sections.create(section_params)
    redirect_to admin_course_path(current_course)
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

  def section_params
    params.require(:section).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def show
  end

  private

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
    <%= simple_form_for @course, url: admin_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/admin/courses/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <% if current_course.image.url %>
    <%= image_tag current_course.image.url, class: 'img-fluid' %>
  <% end %>
  <br />
  <%= link_to 'Preview As Student', course_path(current_course), class: 'btn btn-warning float-right' %>
  <br class="clear" />

  <div class="text-center">
    <%= link_to 'Add a new section', new_admin_course_section_path(current_course), class: 'btn btn-primary btn-lg' %>
  </div>

    <ul>
    <% current_course.sections.each do |section| %>
      <li>
        <%= section.title %>
          <%= link_to 'New Lesson', new_admin_section_lesson_path(section), class: 'float-right btn btn-primary btn-sm' %>
        <ul>
          <% section.lessons.each do |lesson| %>
            <li>
              <b><%= lesson.title %></b>
              -
              <%= lesson.subtitle %>
            </li>
          <% end %>
        </ul>
        <br class="clear" />
      </li>
    <% end %>
  </ul>
  
</div>

app/views/admin/lessons/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new lesson</h1>
  <%= simple_form_for @lesson, url: admin_section_lessons_path(current_section) do |f| %>
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <br />
    <%= f.submit "Add the lesson" %>
    <br />
    <br />
  <% end %>
</div>

app/views/admin/sections/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new section</h1>
    <%= simple_form_for @section, url: admin_course_sections_path(current_course) do |f| %>
    <%= f.input :title %>
    <br />
    <%= f.submit "Add a section", class: 'btn btn-primary' %>
    <br />
    <br />
  <% end %>
</div>

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />

  <% @courses.each do |course| %>
    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h2>
    <% if course.image.url %>
      <%= image_tag course.image.url, class: 'img-fluid' %>
    <% end %>
    <br />
    <div class="row">
      <div class="col-sm-8 col-12">
        <%= course.description %>
      </div>
      <div class="col-sm-4 col-12 text-center">
        <%= link_to 'More Details...', course_path(course), class: 'btn btn-primary btn-large' %>
      </div>
    </div>
    <br class="clear" />
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  <% if @course.image.url %>
    <%= image_tag @course.image.url, class: 'img-fluid' %>
  <% end %>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
        <%= number_to_currency @course.cost %>
      </span>
    </div>

      <% if current_user && current_user == @course.user %>
        <br />
        <br />
        <%= link_to 'Administer', admin_course_path(@course), class: 'btn btn-danger btn-large' %>
      <% end %>

    <div class="col-sm-8 col-12">
      <%= @course.description %>
    </div>
  </div>

  <div class="col-12">
    <% @course.sections.each do |section| %>
      <div class="section">
        <%= section.title %>
        <% section.lessons.each do |lesson| %>
          <div class="lesson">
            <%= link_to lesson_path(lesson) do %>
              <b><%= lesson.title %></b>
              -
              <%= lesson.subtitle %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mantlemakerministries</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-dark bg-dark">
         <%= link_to 'Mantle Maker Ministries', root_url, class: 'navbar-brand' %>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item">
              <%= link_to 'Series', courses_path, class: 'nav-link' %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up!', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>

      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

    <div id="footer">
      <div class="container">
        <b>Footer Here</b>
        <br />
        <%= link_to 'Link', '#' %>
      </div>
    </div>
  </body>
</html>

app/views/lessons/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= current_lesson.title %></h1>
  <p>
    <%= current_lesson.subtitle %>
  </p>
</div>

app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>Title</h1>
    <br />
    <h2>Subtitle</h2>
    <br />
    <%= link_to 'Learn More', courses_path, class: 'btn btn-success' %>
    <br /><br />
  </div>
</div>

<br />
<div class="row feature text-center">
  <div class="col-sm-12 col-lg-4">
    <h3>Feature 1</h3>
    <br />
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing 
    elit. Aenean commodo ligula eget dolor. Aenean massa. 
    Cum sociis natoque penatibus et magnis dis parturient 
    montes, nascetur ridiculus mus. Donec quam felis, 
    ultricies nec, pellentesque eu, pretium quis, sem.</p>
  </div>

  <div class="col-sm-12 col-lg-4">
    <h3>Feature 2</h3>
    <br />
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing 
    elit. Aenean commodo ligula eget dolor. Aenean massa. 
    Cum sociis natoque penatibus et magnis dis parturient 
    montes, nascetur ridiculus mus. Donec quam felis, 
    ultricies nec, pellentesque eu, pretium quis, sem.</p>
  </div>

  <div class="col-sm-12 col-lg-4">
    <h3>Feature 3</h3>
    <br />
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing 
    elit. Aenean commodo ligula eget dolor. Aenean massa. 
    Cum sociis natoque penatibus et magnis dis parturient 
    montes, nascetur ridiculus mus. Donec quam felis, 
    ultricies nec, pellentesque eu, pretium quis, sem.</p>
  </div>
</div>